sudo: required

language: go

go_import_path: github.com/frodenas/stackdriver_exporter

services:
  - docker

env:
  matrix:
    - DOCKER_IMAGE_NAME=frodenas/stackdriver-exporter
  global:
    - secure: h08y3QCxfszjLDu3UirKCiSSEPqfFAkH/2qbce7RXoMpOP1Y6NyNQFNVbdD7HHYy6yFao2b2e0aa/qwBt02dAjhz8U95Fc+ePDTs9QdWD7DA8zl5WeYDusTc0ishTRv8yhN0BvzlsnPjygEbjyRuuuI97gPe7EhhP9VUPPOYKgzZNdbma5xpJ8nK+BGgSbqYPe1Ms77tXfAnBGoHJPlZLuecaQhAOpO0u0bu4EBWMFacpD+7HYAbjETgG9RQJgKTdJgSn/aEVmqs/pX3kZVVfoOOKBcdzzD2mT61sU7P6qZM5lJs1MDR72tYbUmp+BSGMEPRi3oYtq2tEWZlk/xQ6BVy74LnRRdpxmNajazOzgbgSpTB+Vyo3Wza1iPb7pVJ3DJmdZHYOHL3Fe/k6KYCjdHFMxjCtIXxQ0nsBM3hQy5YmstYrZCSne/BKyMr5KNYijiS+YozZHW1fC3jydWPhFMLYtRV5Qir6K2NGk0nOpzZ6HnatcGIWDkFWdbWOOrq2/EmKBdgBY1xxzJnJpaA8OvdRSMNJzjvB7TYC3tyH0L2BefVMEi3aDpvbqy3SJQH8awE3NywGBppo852UDxLlQ+3XXH+sZON5Wu1KK9KWB11ZZkw2QYMncZIooIgobiQn5ysK5GMHIh3A+ZCUyoAyPbshtEzHYyjpG5xRTCg2fQ=
    - secure: s/dEjXQXjPUgm/2hUYwliNGP5CMXPA0RmFGDUF8Hxy6SNnw6AOVofxeTTj7YkxBjQyNzJHnZFeLpoKGgokqMds2vM70vC/I+HM7Xkv6fxER3b52gACuT2SZ4YL/2jHpisBkng74FAGTnyKihWj/OYr3LqPN45NwiDYQ3AbMtkIvqT5M5McU5wu4Q0uQq5Tn97sYzwFg/c7xkc/SLufAqM3NDxjgJWkbAoJCZWR4zgW+1UKUFSEwmrlB6bvnkFvmcDbAsBkXWs7U+xVdhGodsCeDvB826nfhTf3sdIa5kzIiZMl2CSwLynIc94dTx5rY3JsQnyPaxMdgwHgcGl51/oEz3l+FHeCFBFOwAu7T58jzn0P56cFS0+QxaOCI5KflKtVcypcPQfXWlgPRtJENqFQxGfn4NwrjFQFpuk5hK4EwdkGh0q7CE3Ugc2rE7vPIsed/uZvD92NmPvvw6sxonwv7W3KEzKfDuSAT6WQ2gk5IIYTxTU1J3QkuVd/eFPmvDHgj4f+gQmCedPROq104kmfpg1L8cGphR7d2T1tj7C8cvygHAYQp6jqxjrjQd3XsQHVWMAHI/Eu97QAcW+SYL6yd0aKcshijduSVaDNwmXN3ysF1F0WHwTRgKUuK6t5U4993UlKnUM3gIuENWjDilSuILsv2X/kemULyFUCSqSPw=
    - secure: wAwuNlhcFLvczoMBDvI3xN/oWpOY8Isr+Kh57Ubl16K30LzbYJMQB+a+BOcxtiOrYWXv11ZYgmFS3qkRh4yAoc8CzaMn1bZIJFxP4kcWRr/OX9yIxK6bkxzGWjVuygAUBqIC3kOdz3pbLcKRI4YqJAPaC4wP857aEuXWVViGWej8w8cu54t739LtU8q5CHFYUF+c/TIuzHpXPOo24dH3hZpD3iccSjwLo0g2ox/xRLmdkRvU5r9Od0cZevDqkVC5QDdcKYgbCHn7YntSBTtHQwTYflLkXrgJFA8iLLQH04dlxJ2TX4+ULB6FdauYl4oOpIkJrL83sDIhoPcLiq7QKHLgS+Z+QPnb0a5VzXECWjwGS5wHEF2RinImKnDm6ZBj+uJm6jjc8y9ndtsq51mVvXUfRbztIeKOMVP1Rhknp8jrYf0dzvtm1ebjdIqH3zlWnubIYaQ/BaRquw3HpZILALMnE0HvEitqeXv+BfQvfhDzxMw6pfdgFeC6P2sVJU8wANRcqgQhGeyPWZWHy6ARNlCxVYpFpL4ER5cixVJQ1TCkAtKLXxmfxZj5Wf0JXk4q6yLz5gmtfTYdZ5FNpdw9FCwWxJbI3DA34ZieWbrQOHV09BF3eSg8BECpjzvUzeZ8KoNC7z2B1kfLoxaHMb4Q66S6VFY+sVj/G+7nYhezQZI=

jobs:
  include:
    - stage: tests
      script: make test
    - stage: docker image
      script:
        - make crossbuild
        - ln -s .build/linux-amd64/stackdriver_exporter stackdriver_exporter
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
          fi
        - |
          if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
          fi
        - docker images
        - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
        - docker push $DOCKER_IMAGE_NAME
