sudo: required

language: go

go_import_path: github.com/frodenas/stackdriver_exporter

services:
  - docker

jobs:
  include:
    - stage: tests
      script: make test
    - stage: build
      script: make crossbuild
    - stage: build docker image
      script:
        - ln -s .build/linux-amd64/stackdriver_exporter stackdriver_exporter
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME
          fi
        -  docker images